//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerField()
        {
            this.MatrixAnswers = new HashSet<MatrixAnswer>();
        }
    
        public int Id { get; set; }
        public int AnswerSurvayId { get; set; }
        public int FieldId { get; set; }
        public string Type { get; set; }
        public string Answer { get; set; }
        public string IncludeOther { get; set; }
        public string AttachmentType { get; set; }
    
        public virtual AnswerSurvay AnswerSurvay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixAnswer> MatrixAnswers { get; set; }
        public virtual Field Field { get; set; }
    }
}
