//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerSurvay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerSurvay()
        {
            this.AnswerFields = new HashSet<AnswerField>();
        }
    
        public int Id { get; set; }
        public int SurvayId { get; set; }
        public int SurvayTypeID { get; set; }
        public int DeviceId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int ClientId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerField> AnswerFields { get; set; }
        public virtual Client Client { get; set; }
        public virtual DeviceManager DeviceManager { get; set; }
        public virtual Survay Survay { get; set; }
        public virtual SurvayType SurvayType { get; set; }
    }
}
