//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldDependant
    {
        public int Id { get; set; }
        public int FieldId { get; set; }
        public Nullable<int> DependantFieldId { get; set; }
        public int DependantType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Value { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Field Field1 { get; set; }
    }
}
