//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixAnswer
    {
        public int Id { get; set; }
        public int AnswerFieldId { get; set; }
        public string Row { get; set; }
        public string HeaderList { get; set; }
    
        public virtual AnswerField AnswerField { get; set; }
    }
}
