//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvayTarget
    {
        public int Id { get; set; }
        public int SurvaySettingId { get; set; }
        public int ProvinceId { get; set; }
        public int DistrictId { get; set; }
        public int Target { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public int OptionId { get; set; }
    
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual SurvaySetting SurvaySetting { get; set; }
    }
}
