//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurvayArm.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurvayArmDbContext : DbContext
    {
        public SurvayArmDbContext()
            : base("name=SurvayArmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<FieldOption> FieldOptions { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<SurvaySetting> SurvaySettings { get; set; }
        public virtual DbSet<SurvaySupervisor> SurvaySupervisors { get; set; }
        public virtual DbSet<SurvayType> SurvayTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<SurvayTarget> SurvayTargets { get; set; }
        public virtual DbSet<UserSurvay> UserSurvays { get; set; }
        public virtual DbSet<Survay> Survays { get; set; }
        public virtual DbSet<MatrixHeader> MatrixHeaders { get; set; }
        public virtual DbSet<MatrixRow> MatrixRows { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<AnswerField> AnswerFields { get; set; }
        public virtual DbSet<DeviceManager> DeviceManagers { get; set; }
        public virtual DbSet<AnswerSurvay> AnswerSurvays { get; set; }
        public virtual DbSet<MatrixAnswer> MatrixAnswers { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<FieldDependant> FieldDependants { get; set; }
    }
}
